# Generated by Django 5.2.15 on 2026-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_cardapio_produto_cardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
