# Generated by Django 5.2.15 on 2026-07-17 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_cardapio_banner_cardapio_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardapios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='cardapio',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='cardapio.cardapio'),
            preserve_default=False,
        ),
    ]
