# Generated by Django 5.2.15 on 2026-07-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_cardapio_dono_categoria_cardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='whats',
            field=models.CharField(blank=True, null=True),
        ),
    ]
